export const sampleProducts = [
  {
    "ProductID": 1,
    "groupName": "تست",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18,
  }, {
    "ProductID": 1,
    "groupName": "گروه2",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18
  },{
    "ProductID": 1,
    "groupName": "گروه3",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18,
  },
  {
    "ProductID": 1,
    "groupName": "تست4",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18,
  },{
    "ProductID": 1,
    "groupName": "",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18,
  },
  {
    "ProductID": 1,
    "groupName": "",
    "groupDescription": 1,
    "userAccess": 1,
    "Condition": "",
    "numberMembers": 18,
  }];




export const products = [{
  "ProductID": 1,
  "name": "علی",
  "lastName": "ابراهیمی",
  "company": "",
  "tell": "5855452",
  "email": "",
  "Gender": "مرد",
  "description": "",
  "Options": "",
  "Discontinued": false,
}, {
  "ProductID": 2,
  "name": "حسن",
  "lastName": "حسنی",
  "company": "",
  "tell": "5746746541",
  "email": "",
  "Gender": "",
  "description": "",
  "Options": "",
  "Discontinued": false,
}, {
  "ProductID": 3,
  "name": "مجید",
  "lastName": "مجیدی",
  "company": "",
  "tell": "57464656",
  "email": "",
  "Gender": "",
  "description": "",
  "Options": 10,
  "Discontinued": false,
}, {
  "ProductID": 4,
  "name": "حمی",
  "lastName": "",
  "company": "",
  "tell": "54354354",
  "email": "",
  "Gender": "",
  "description": "",
  "Options": "",
  "Discontinued": false,
}, {
  "ProductID": 5,
  "name": "محمد",
  "lastName": "محمدی",
  "company": "",
  "tell": "645534",
  "email": "",
  "Gender": "",
  "description": "",
  "Options": "",
  "Discontinued": false,
}];
